### ISSUE TITLE
[HELP] 响应图片未能正确显示

### ISSUE THREAD

**Issue by Cvandia** [lgc-NB2Dev/nonebot-plugin-eitherchoice#1]
## 怎么出现的
指令发送后出现
![Cache_2f0c14ce3333a0ef](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/106718176/32a02ffd-b3df-4c60-bc65-2ea3108849ec)

**Comment by lgc2333** [comment]
已修复，请更新 [v0.1.2](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/releases/tag/v0.1.2)
