### ISSUE TITLE
返回图片只显示[Object Object]

### ISSUE THREAD

**Issue by ElainaFanBoy** [lgc-NB2Dev/nonebot-plugin-eitherchoice#3]
昨天还没事，而且最近好像经常超时，现在一直报object了，这是官方问题还是我这边的问题

**Comment by lgc2333** [comment]
已修复，请更新 [v0.1.2](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/releases/tag/v0.1.2)

**Comment by ElainaFanBoy** [comment]
> 已修复，请更新 [v0.1.2](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/releases/tag/v0.1.2)

辛苦了
