### ISSUE TITLE
生成图片清晰度较低与排版

### ISSUE THREAD

**Issue by yhrbjsy** [lgc-NB2Dev/nonebot-plugin-eitherchoice#4]
调高EITHER_CHOICE_PIC_WIDTH还有代码内viewport的height也仅会让图片整体宽度更大，高度反而会降低，清晰度并没有变化。可否有方法提高生成图片的清晰度呢？
![c46ff194dc9ad7f333b815c22dc1cfc8](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/59187833/9620753b-3924-40ef-ba53-d2bb47af00d2)
![ce72def968cc23c1e477c13328ffc76f](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/59187833/ab1d01a4-9d8e-4c10-9d0f-2832841d4873)
![22d2fc6d12bc9e85665c4949ed17f63b](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/59187833/a1c6856f-503c-479f-bbd9-967e7685086c)

**Comment by yhrbjsy** [comment]
找到问题在哪儿了，get_new_page的device_scale_factor传一个2.0就好了，不知道为啥默认的2.0没生效...
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/59187833/85d612c8-a493-4938-b46a-67ec64d9381c)

**Comment by yhrbjsy** [comment]
还有一个就是对比条数大于4时的显示问题
![image](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/59187833/3a5116da-2736-4c12-8508-b5ea3f104ccf)

**Comment by lgc2333** [comment]
> 还有一个就是对比条数大于4时的显示问题 ![image](https://user-images.githubusercontent.com/59187833/250288740-3a5116da-2736-4c12-8508-b5ea3f104ccf.jpeg)

这个不是显示问题，是本来就这样

还有图片清晰度问题不打算修
