### ISSUE TITLE
playwright加载页面超时

### ISSUE THREAD

**Issue by IllusiveBull** [lgc-NB2Dev/nonebot-plugin-eitherchoice#5]
![KT%F`6 TQ{)6JA3IUMWW XR](https://github.com/lgc-NB2Dev/nonebot-plugin-eitherchoice/assets/112180508/83bc767b-931a-4315-927a-f23650cb0980)

如图(抱歉只存了截图)playwright加载页面有一个30秒的默认timeout，可能是我服务器性能太差导致的？把data_source.py的第56行改为  
`        await page.goto(RES_PATH.as_uri(),timeout=0)`  
后解决了

**Comment by lgc2333** [comment]
怪了，之后加个配置项吧

**Comment by lgc2333** [comment]
怪了，之后加个配置项吧

**Comment by lgc2333** [comment]
诶不对，你这是截图超时来着

**Comment by IllusiveBull** [comment]
> 诶不对，你这是截图超时来着

但确实改了goto那行就解决了，改之前每次都超时，很怪

**Comment by lgc2333** [comment]
不想做，先关了
